### ISSUE TITLE
Multiple listing of server and user name when changing stages

### ISSUE THREAD

**Issue by tecpromotion** [mittwald/spaces-feedback#7]
**Expected result:** 
Server and user name are listed multiple times when changing Spaces.
The SSH command changes correctly.

**Actual result:**
Output of server and user name not multiple times.
The SSH command changes correctly.

**Additional Information**
<img width="838" alt="screenshot 2018-11-03 12 16 22" src="https://user-images.githubusercontent.com/1752513/47951578-e36a8c80-df62-11e8-9825-3709419e7e49.png">

**Comment by ins0** [comment]
Fixed, will be deployed with next live sync. Thanks @tecpromotion
