### ISSUE TITLE
No SSH Login on recovered accounts

### ISSUE THREAD

**Issue by tecpromotion** [mittwald/spaces-feedback#8]
A LAMP stack was restored from a backup and a new stage was created in the step.

**Expected result:**
SSH login works for recovered accounts from a backup. No password is used.

**Actual result:**
SSH login not working for recovered accounts from a backup. A password is requested in the console.

**Additional Information**
<img width="513" alt="screenshot 2018-11-03 12 25 30" src="https://user-images.githubusercontent.com/1752513/47951629-933ffa00-df63-11e8-9ce1-bcf1a5e76312.png">

**Comment by martin-helmich** [comment]
We've had an issue where SSH keys were not synchronized into newly created Spaces and/or stages. Should be resolved now.
